language: node_js
node_js:
- node
script:
- npm test
notifications:
  email: false
install:
- npm install
deploy:
  provider: heroku
  app: weblabnodetest
  api_key:
    secure: pLkRXYsPGOO+x9FI+/wq8ogMrFXzzHp2tsC5mLq4ehznr0/t5irqr2GMad2YcogRvdeYWlyKIpwlIkEtehduteyYBrBJChPQgbDSoBpjJlfl0GsotUEPgAmL3iDETzD+MeoHV0ugrRGHdDMBGtqtAyk2U02UIH8Z9qfrs2bR0MuoERfAs0MjBU+R6hoj83u9mojFaJtK18vLB4br5UxqA1cCI5loI5zcywRbYxs/MUmXZJpxbkUFFLT48RKpYa3OK9kfDFhSDv3R6G9zJ4m5Ay8Gq+Ij2GA+SScgkAKafsDq0MtarSa/Rdm0Iu8YViDoclJ5u7AAVoYXSv0ciT+KbHS21HkHx/Hva2xo38+Dtob8QNXTXERIPYPtjpHLASZmZwC3h4xmSCRL11wd8dXnfpTFoPFQ4hSkHjzJctTAojDz3QnGvIfanwYpFP9IdKtPQLi00dxonJ2LtxxNJK1ddW6A/tLImm2bklES04/HqwHJwLNqqj284+cjDGkwLrzwYiYQSeORFDh+vUV9uf8gf3qZ0kzPOCJ5OnUM3pvrd16qiAAxImPEFVTIDYi4PWLHEfj9cxQZwbdmqgCF50AhwNUIblBcu/y0g+sA9G5YxsAZ+Or9cdrDdV1hbMmRAzqPWOwt9gLSVBlUZAw70G53I26UmsEyltXrf/n7y5HTVg=