language: node_js
node_js:
- node
script:
- npm test
notifications:
  email: false
install:
- npm install
deploy:
  provider: heroku
  app: weblabnodetest
  api_key:
    secure: f7d54c06-b98e-4c55-9d51-b73459689f76
  app: weblabnodetest
  on: 
    repo: PauLOk777/basic-REST-API